### ISSUE TITLE
Notice: Undefined index 

### ISSUE THREAD

**Issue by DevinWalker** [gndev/sunrise#1]
With WP Debug turned on I'm seeing a lot of various Notice errors in the dashboard. Granted, they are only notices but it would be nice if this were fixed. For instance, after activation:

![widget-notices-errors](https://f.cloud.github.com/assets/1571635/1047404/da3acd88-1068-11e3-9fc3-cbd89007784c.jpg)

**Comment by tlongren** [comment]
Closing this issue as @gndev confirmed via email that he pushed a fix for this quite some time ago.
